# Generated by Django 3.2.6 on 2023-01-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_delete_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='SocialApp.user')),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='SocialApp.user')),
            ],
        ),
    ]
