# Generated by Django 3.2.6 on 2023-01-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0004_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='base_user',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
