# Generated by Django 3.2.6 on 2023-01-10 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialApp', '0005_auto_20230110_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('nposts', models.IntegerField()),
                ('nfollowers', models.IntegerField()),
                ('nfollowing', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('general', 'General'), ('bussiness', 'Bussiness')], max_length=30)),
                ('luser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
