# Generated by Django 3.2.6 on 2023-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_comments_followers_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimg',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
