# Generated by Django 3.2.6 on 2023-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0008_alter_user_pimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimg',
            field=models.ImageField(upload_to='css/img/'),
        ),
    ]
