# Generated by Django 3.2.6 on 2023-01-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0013_auto_20230110_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='base_user',
        ),
    ]
