# Generated by Django 3.2.6 on 2023-01-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0014_remove_followers_base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='base_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='SocialApp.user'),
        ),
    ]
