# Generated by Django 3.2.6 on 2023-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0017_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pimg',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
