# Generated by Django 3.2.6 on 2023-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0018_auto_20230112_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimg',
            field=models.ImageField(blank=True, default='', upload_to='static/img'),
        ),
    ]
