# Generated by Django 3.2.6 on 2023-01-12 16:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0021_alter_user_pimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimg',
            field=models.ImageField(blank=True, default='', storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to=''),
        ),
    ]
